export const AUTHORS: Object[] = [
  { givenName: 'Forest', familyName: 'Baumbach' },
  { givenName: 'Hazle', familyName: 'McClure' },
  { givenName: 'Edmond', familyName: 'Kovacek' },
  { givenName: 'Nils', familyName: 'Ruecker' },
  { givenName: 'Bria', familyName: 'Auer' },
  { givenName: 'Maymie', familyName: 'Sanford' },
  { givenName: 'Joesph', familyName: 'Kunde' },
  { givenName: 'Dayne', familyName: 'Dach' },
  { givenName: 'Bridie', familyName: 'Turcotte' },
  { givenName: 'Derick', familyName: 'Cassin' },
];

export const BOOKS: Object[] = [
  {
    authorId: 7,
    rating: 2.1,
    title: 'Deserunt',
    description:
      'Reprehenderit quisquam quaerat saepe dolorem error molestiae.',
    datePublished: '2014-07-22',
  },
  {
    authorId: 6,
    rating: 2.8,
    title: 'At',
    description: 'Ullam est soluta ipsa id.',
    datePublished: '1977-02-10',
  },
  {
    authorId: 5,
    rating: 4.5,
    title: 'Aliquid',
    description: 'Qui ipsa dolores quis.',
    datePublished: '1970-09-10',
  },
  {
    authorId: 0,
    rating: 2.9,
    title: 'Vitae',
    description:
      'Quo veritatis doloribus in voluptatem maiores vitae praesentium.',
    datePublished: '1989-03-27',
  },
  {
    authorId: 4,
    rating: 2.6,
    title: 'Minus',
    description: 'Voluptas nihil nihil quam vero aut.',
    datePublished: '1987-01-20',
  },
  {
    authorId: 1,
    rating: 3.2,
    title: 'Explicabo',
    description: 'Aperiam sed eligendi iusto a quidem.',
    datePublished: '2010-10-03',
  },
  {
    authorId: 5,
    rating: 1.5,
    title: 'Dolorem',
    description: 'Ipsa dolor dolorem sed iste enim reiciendis.',
    datePublished: '2020-03-26',
  },
  {
    authorId: 4,
    rating: 3.5,
    title: 'Quaerat',
    description: 'Tenetur quasi sit explicabo quis mollitia nam.',
    datePublished: '1986-07-21',
  },
  {
    authorId: 1,
    rating: 2.4,
    title: 'Eos',
    description:
      'Et sed corrupti ipsam maxime officiis numquam veritatis quasi.',
    datePublished: '2004-02-15',
  },
  {
    authorId: 1,
    rating: 2.9,
    title: 'Placeat',
    description: 'Delectus et laudantium delectus.',
    datePublished: '1976-05-11',
  },
  {
    authorId: 6,
    rating: 1.5,
    title: 'Et',
    description: 'Soluta aut hic vitae a vero tenetur.',
    datePublished: '2011-04-22',
  },
  {
    authorId: 5,
    rating: 3.1,
    title: 'Rem',
    description:
      'Debitis fugit autem temporibus perferendis culpa omnis nam et.',
    datePublished: '1990-02-17',
  },
  {
    authorId: 1,
    rating: 3.3,
    title: 'Facere',
    description: 'Eligendi quas qui expedita accusamus.',
    datePublished: '2002-01-17',
  },
  {
    authorId: 4,
    rating: 1.2,
    title: 'At',
    description: 'Molestias fuga temporibus voluptas necessitatibus amet.',
    datePublished: '2011-05-18',
  },
  {
    authorId: 7,
    rating: 4.6,
    title: 'Consectetur',
    description: 'Ea omnis qui excepturi et quos nihil.',
    datePublished: '2010-12-16',
  },
  {
    authorId: 1,
    rating: 4.4,
    title: 'Consequuntur',
    description: 'Similique dolorem dignissimos quia fuga dignissimos.',
    datePublished: '2011-12-26',
  },
  {
    authorId: 4,
    rating: 1.1,
    title: 'Voluptas',
    description: 'Qui aliquid voluptas omnis qui vel.',
    datePublished: '2019-08-04',
  },
  {
    authorId: 9,
    rating: 4.7,
    title: 'Autem',
    description: 'Omnis eos est quis deserunt est eius.',
    datePublished: '1971-12-23',
  },
  {
    authorId: 8,
    rating: 1.6,
    title: 'Et',
    description: 'Incidunt qui voluptatum officia velit iusto sit.',
    datePublished: '2005-07-20',
  },
  {
    authorId: 1,
    rating: 1.4,
    title: 'Quo',
    description: 'Sit qui ut nostrum quia.',
    datePublished: '1973-05-02',
  },
  {
    authorId: 8,
    rating: 2.1,
    title: 'Sunt',
    description: 'Magni eligendi in ut iste veniam amet.',
    datePublished: '1989-08-23',
  },
  {
    authorId: 9,
    rating: 3.7,
    title: 'Similique',
    description: 'Quia quia aut consequatur reiciendis maxime.',
    datePublished: '2020-05-24',
  },
  {
    authorId: 1,
    rating: 2.4,
    title: 'Saepe',
    description: 'Rerum aut nam dolor modi.',
    datePublished: '2006-09-17',
  },
  {
    authorId: 9,
    rating: 1,
    title: 'Velit',
    description: 'Accusantium aperiam earum quae nihil veniam et.',
    datePublished: '2011-09-22',
  },
  {
    authorId: 5,
    rating: 1.4,
    title: 'Repudiandae',
    description: 'Suscipit porro cupiditate et sint.',
    datePublished: '1990-07-22',
  },
  {
    authorId: 1,
    rating: 4.6,
    title: 'Ipsum',
    description: 'Vitae et et sed in.',
    datePublished: '1987-01-14',
  },
  {
    authorId: 5,
    rating: 2.3,
    title: 'Quod',
    description: 'Hic porro et aut.',
    datePublished: '2018-05-12',
  },
  {
    authorId: 7,
    rating: 3.3,
    title: 'Minima',
    description: 'Voluptas vitae facere rem molestiae nobis odit non.',
    datePublished: '2002-03-30',
  },
  {
    authorId: 9,
    rating: 3.5,
    title: 'Voluptatem',
    description: 'Iusto qui optio cupiditate omnis consequuntur.',
    datePublished: '2004-02-05',
  },
  {
    authorId: 4,
    rating: 2.9,
    title: 'Ut',
    description: 'Autem sed iste autem sit inventore.',
    datePublished: '1996-08-23',
  },
  {
    authorId: 2,
    rating: 2.6,
    title: 'Quisquam',
    description: 'Hic magnam incidunt in voluptatem voluptatem magni quis.',
    datePublished: '1973-05-19',
  },
  {
    authorId: 6,
    rating: 3,
    title: 'Repellendus',
    description: 'Tenetur culpa enim nostrum nam sit sit.',
    datePublished: '1998-07-10',
  },
  {
    authorId: 2,
    rating: 2,
    title: 'Et',
    description: 'Et a quia quia asperiores in rem.',
    datePublished: '1989-10-20',
  },
  {
    authorId: 2,
    rating: 1.6,
    title: 'Omnis',
    description: 'Recusandae dolore labore et at provident.',
    datePublished: '1984-03-10',
  },
  {
    authorId: 8,
    rating: 2.1,
    title: 'Vel',
    description: 'Voluptatem rem sunt ducimus.',
    datePublished: '2004-09-05',
  },
  {
    authorId: 4,
    rating: 1.1,
    title: 'Autem',
    description: 'Ut quo illo ex id.',
    datePublished: '1973-01-11',
  },
  {
    authorId: 5,
    rating: 2.5,
    title: 'Odit',
    description: 'Totam saepe cum et voluptatum.',
    datePublished: '2004-05-17',
  },
  {
    authorId: 1,
    rating: 3.9,
    title: 'Voluptate',
    description: 'Quasi molestiae repudiandae id officiis.',
    datePublished: '1983-11-13',
  },
  {
    authorId: 4,
    rating: 3.7,
    title: 'Sit',
    description: 'Deserunt id neque culpa tempora corporis quos.',
    datePublished: '1983-07-05',
  },
  {
    authorId: 6,
    rating: 4.6,
    title: 'Sit',
    description: 'Eaque minus id modi tempora quia eos.',
    datePublished: '1983-12-31',
  },
  {
    authorId: 0,
    rating: 1,
    title: 'Ab',
    description: 'Unde vel consequatur enim dignissimos sunt maiores.',
    datePublished: '2011-07-20',
  },
  {
    authorId: 3,
    rating: 4.5,
    title: 'Eos',
    description: 'Qui iusto expedita praesentium ipsam vitae eum quia.',
    datePublished: '2020-06-20',
  },
  {
    authorId: 5,
    rating: 2.2,
    title: 'Debitis',
    description: 'Ut qui qui doloremque sunt.',
    datePublished: '1983-12-24',
  },
  {
    authorId: 2,
    rating: 2.2,
    title: 'Perferendis',
    description: 'Magnam molestias excepturi cum nemo.',
    datePublished: '1993-06-13',
  },
  {
    authorId: 7,
    rating: 1.6,
    title: 'Numquam',
    description: 'Laudantium hic ut voluptatibus iste quia.',
    datePublished: '1998-06-23',
  },
  {
    authorId: 1,
    rating: 1.7,
    title: 'Et',
    description: 'Tenetur pariatur eum esse unde consequuntur voluptatem qui.',
    datePublished: '1978-07-10',
  },
  {
    authorId: 2,
    rating: 2.2,
    title: 'Officia',
    description: 'Aut magni modi explicabo.',
    datePublished: '1970-12-29',
  },
  {
    authorId: 8,
    rating: 4.4,
    title: 'Maiores',
    description: 'Architecto aliquam sunt rerum molestiae.',
    datePublished: '1973-05-22',
  },
  {
    authorId: 8,
    rating: 1.1,
    title: 'Harum',
    description: 'Dolorum aut corrupti dolorem quia placeat voluptatem sit.',
    datePublished: '1988-10-15',
  },
  {
    authorId: 4,
    rating: 4.6,
    title: 'Rerum',
    description:
      'Aspernatur eligendi illum reprehenderit accusamus molestiae impedit.',
    datePublished: '2010-10-31',
  },
];
